version: 0.2

# Environment variables that are available to the build process
env:
  variables:
    NODE_ENV: production

# Phases of the build: install, pre_build, build, and post_build
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands...
      # Add any pre-build commands here
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running post-build commands...
      # Add any post-build commands here, such as running tests, publishing artifacts, etc.

# Artifacts that CodeBuild will produce
artifacts:
  files:
    - 'dist/**/*'
  discard-paths: yes

