version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker/password
    DOCKER_REGISTRY_URL: /myapp/docker-credential/docker_registry_url
phases:
  install:
    runtime-versions:
      python : 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - cd Flaskproject
      - echo "Building the Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL"/myapp:latest .
      - docker push "$DOCKER_REGISTRY_URL"/myapp:latest
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  base-directory: build
